services:
  moon-shell:
    build:
      context: .
      dockerfile: Dockerfile
    image: moon-shell:local
    container_name: moon-shell
    command: ["--config=/srv/config.yml"]
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - .:/srv/
